### ISSUE TITLE
Matrix.UnusedResourcesTask---The Resource declarations file 'R.txt' is not legal!

### ISSUE THREAD

**Issue by tracymac7** [Tencent/matrix#11]
执行apkChecker jar 通过config文件传递参数 发生如下错误

[ERROR][Matrix.ApkJob]Task executor execute with error:Matrix.UnusedResourcesTask---The Resource declarations file 'R.txt' is not legal!
com.tencent.matrix.apk.model.exception.TaskInitException: Matrix.UnusedResourcesTask---The Resource declarations file 'R.txt' is not legal!
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.init(UnusedResourcesTask.java:106)
	at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:492)
	at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:469)
	at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
	at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)

**Comment by jqctop1** [comment]
@tracymac7 你传递的config文件内容是什么样？贴出来看看？

**Comment by tracymac7** [comment]
config里面R文件路径有误 忽略

**Comment by xuIcream** [comment]
我的也有这个问题，请问这个R文件路径是哪个呢 @tracymac7
