### ISSUE TITLE
编译异常:com.android.build.api.transform.TransformException: 

### ISSUE THREAD

**Issue by SilenceDut** [Tencent/matrix#112]
```
异常类型：编译异常

matrix版本：0.4.7

gradle版本： 3.1.4

问题描述：编译失败

```
堆栈/日志：

...
[ERROR][Matrix.FileUtil]file op readFileAsString e type:FileNotFoundException, e msg:/Users/.../app/matrixTrace/blackMethodList.txt (No such file or directory), filePath:/Users/.../app/matrixTrace/blackMethodList.txt
...
[INFO][Matrix.MethodCollector][collect] 72472 method from /app/build/matrix_output/Debug.methodmap
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
...
[ERROR][Matrix.MethodTracer][traceMethodFromJar] err! /Users/.../app/build/matrix_output/classes/MatrixTraceTransform/cloud_push_service-2.7.05.160901-nobaidu_f8d8430dbfb3bb96bb89c3592bebb3c7d61d8007.jar

AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow","sources":[{}]}

Caused by: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:222)
        at com.android.build.gradle.internal.transforms.DexTransform$transform$0.call(Unknown Source)
        at com.tencent.matrix.plugin.transform.MatrixTraceTransform.transform(MatrixTraceTransform.groovy:130)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)

* What went wrong:
Attempted re-init of type{byte[]}

* Exception is:
java.lang.IllegalStateException: Attempted re-init of type{byte[]}
        at com.android.dx.rop.cst.CstType.internInitial(CstType.java:128)

**Comment by changelcai** [comment]
应该是这个目录下的文件被删掉了，导致编译时读不到。

**Comment by lijiangdong** [comment]
@SilenceDut 这个问题是怎么解决的啊。
