### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference

### ISSUE THREAD

**Issue by seasonfif** [Tencent/matrix#127]
03-06 22:32:07.184   330   489 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference
03-06 22:32:07.184   330   489 E AndroidRuntime:   at com.tencent.matrix.trace.tracer.FPSTracer.doReport(FPSTracer.java:289)
03-06 22:32:07.184   330   489 E AndroidRuntime:   at com.tencent.matrix.trace.tracer.FPSTracer.onTimeExpire(FPSTracer.java:152)
03-06 22:32:07.184   330   489 E AndroidRuntime:   at com.tencent.matrix.trace.schedule.LazyScheduler$RetryRunnable.run(LazyScheduler.java:83)
03-06 22:32:07.184   330   489 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:891)
03-06 22:32:07.184   330   489 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:102)
03-06 22:32:07.184   330   489 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:207)
03-06 22:32:07.184   330   489 E AndroidRuntime:   at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by runforprogram** [comment]
new TracePlugin 的时候没有传config
