### ISSUE TITLE
新版本0.5.1集成以后，一启动就crash。。。

### ISSUE THREAD

**Issue by fvdcx** [Tencent/matrix#191]
@txfelixzhou @changelcai 
`2019-04-17 20:22:35.610 6402-6402/ E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.StackOverflowError: stack size 8MB
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
2019-04-17 20:22:35.612 6402-6402/AndroidRuntime:     at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:3)`

**Comment by oceanzhang01** [comment]
我这边也是，有解决方法吗 ？

**Comment by Simon986793021** [comment]
+1 ，有解决方案了吗

**Comment by changelcai** [comment]
更新到0.5.2，已经fix这个问题。

**Comment by Notzuonotdied** [comment]
折腾了好久，解决了，升级0.5.2就解决了@txfelixzhou 麻烦更新下readme吧，这样大家也不用每次都躺着个坑。

**Comment by xushaojie** [comment]
升级到0.5.2

**Comment by wjq123521** [comment]
已入坑，更新下Readme+1

**Comment by buyiyun** [comment]
我也遇到这个问题

**Comment by ly20050516** [comment]
升级到 0.5.2 了，仍然出现一样的问题呢

**Comment by changelcai** [comment]
0.5.2应该是不会有这个问题的，确认下是不是已经升级的，报错还是一样的堆栈？

**Comment by changelcai** [comment]
> 升级到 0.5.2 了，仍然出现一样的问题呢

 0.5.2 是确认已经修复的，再检查确认下升级到 0.5.2 ，报错还是一样的堆栈吗？

**Comment by ly20050516** [comment]
已经解决了。不好意思，是我的 root project 中的 classpath 没同步到。谢谢
