### ISSUE TITLE
sample-android  TestTraceMainActivity 打开崩溃。WindowManager权限问题。

### ISSUE THREAD

**Issue by jyy195822328** [Tencent/matrix#204]
异常类型：app 运行时异常

手机型号: 三星J7

手机系统版本：android 8.1

matrix版本: 0.5.1

gradle版本: 3.0.0
问题描述：sample-android   TestTraceMainActivity 打开崩溃。WindowManager权限api23以上权限问题。
```
 Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@8619254 -- permission denied for window type 2038
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1006)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:384)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:101)
        at com.tencent.matrix.trace.view.FrameDecorator.show(FrameDecorator.java:121)
        at sample.tencent.matrix.trace.TestTraceMainActivity.onCreate(TestTraceMainActivity.java:60)
```

**Comment by WJRye** [comment]
1.在AndroidManifest.xml中添加权限：
`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />`
2.进入系统设置，在应用matrix-android权限中选择打开“悬浮窗”权限。
