### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by xuIcream** [Tencent/matrix#21]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```
异常类型：app 运行时异常/编译异常

手机型号：如: Nexus 5(如是编译异常，则可以不填)

手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)

matrix版本：如: 0.4.7

gradle版本：如: 3.0.0

问题描述：如：在 android O 出现系统不兼容 

堆栈/日志：
1. 如是编译异常，请在执行 gradle 命令时，加上 --stacktrace;
2. 日志我们需要过滤" Matrix. "关键字;
```

提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种 issue 也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Matrix 是一个开源项目，希望大家遇到问题时要学会先思考，看看 Sample 与 Matrix 的源码，更鼓励大家给我们提 pr .

**Comment by xuIcream** [comment]
[DEBUG][Matrix.UnStrippedSoCheckTask]lib: libsgmain.so is not stripped
[ERROR][Matrix.ApkJob]Task executor execute with error:java.lang.StackOverflowError
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:496)
	at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:469)
	at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
	at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)
Caused by: java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.remove(HashMap.java:799)
	at java.util.HashSet.remove(HashSet.java:236)
	at java.util.AbstractSet.removeAll(AbstractSet.java:174)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:400)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)
	at com.tencent.matrix.apk.model.task.UnusedResourcesTask.readChildReference(UnusedResourcesTask.java:402)

**Comment by xuIcream** [comment]
还是有出现

**Comment by astrozhou** [comment]
请仔细阅读 Issue 提问方式，尽量描述清楚问题。例如贴的日志是怎样操作出来的，在什么环境下。谢谢

**Comment by xuIcream** [comment]
> @xuIcream 这个apk方便提供一下吗？

不好意思，app 还没发布，暂时还提供不了 。

**Comment by jqctop1** [comment]
@xuIcream 那麻烦将完整的运行日志输出到一个文件里然后传上来？

**Comment by xuIcream** [comment]
[log.zip](https://github.com/Tencent/matrix/files/2716951/log.zip)
@jqctop1 截取了后面部分，请查看。

**Comment by jqctop1** [comment]
@xuIcream https://github.com/Tencent/matrix/issues/71

可以看下这个issue，可能跟你的是同一个原因，有两个同名的资源，然后UnusedResourcesTask以为资源循环引用了。

具体，你可以在UnusedResourcesTask中加这样的日志来看看是哪个资源解析出错了

![image](https://user-images.githubusercontent.com/15994990/50757517-8a88de80-129a-11e9-8dd2-41d5b8e30d94.png)
