### ISSUE TITLE
matrix-apk-version Exception: Dex version 038 is not supported

### ISSUE THREAD

**Issue by HanLinlin** [Tencent/matrix#219]
jar 包 运行时异常
apk是 Q 编译的

是否有更新支持 Dex38 及 以上版本？

[INFO][Matrix.ResProguardCheckTask]directory color has a non-proguard name!
[DEBUG][Matrix.MultiSTLCheckTask]lib: libjpegkit.so has stl link
[DEBUG][Matrix.UnusedAssetsTask]find all assets count: 241
[DEBUG][Matrix.UnStrippedSoCheckTask]lib: libjpegkit.so is not stripped
[ERROR][Matrix.ApkJob]Task executor execute with error:com.tencent.matrix.apk.model.exception.TaskExecuteException: Dex version 038 is not supported
java.util.concurrent.ExecutionException: com.tencent.matrix.apk.model.exception.TaskExecuteException: Dex version 038 is not supported
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:501)
        at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:474)
        at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
        at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)
Caused by: com.tencent.matrix.apk.model.exception.TaskExecuteException: Dex version 038 is not supported
        at com.tencent.matrix.apk.model.task.UnusedAssetsTask.call(UnusedAssetsTask.java:208)
        at com.tencent.matrix.apk.model.task.UnusedAssetsTask.call(UnusedAssetsTask.java:53)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jf.dexlib2.util.DexUtil$UnsupportedFile: Dex version 038 is not supported
        at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:94)
        at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:71)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.fromInputStream(DexBackedDexFile.java:110)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:97)
        at com.tencent.matrix.apk.model.task.UnusedAssetsTask.decodeCode(UnusedAssetsTask.java:120)
        at com.tencent.matrix.apk.model.task.UnusedAssetsTask.call(UnusedAssetsTask.java:196)

**Comment by HanLinlin** [comment]
异常类型： app 运行时异常
手机型号： NA
手机系统版本： NA
matrix 版本：0.4.10
gradle 版本： NA

堆栈、日志：请见 issue

**Comment by jqctop1** [comment]
好的，这个正在修改和测试中哈

**Comment by 3805306** [comment]
我在P版本上编译的APK也发现了这个问题，可以的化，发个临时的jar包给我们也验证下 3805306@qq.com

**Comment by 3805306** [comment]
O版本上编译的APK没有问题，是使用的apktools。jar版本太低导致的么

**Comment by hfutgl** [comment]
这个问题我早就报过 一直没改 你可以自己更新jar包

**Comment by JackyAndroid** [comment]
@hfutgl 你升级apktool到哪个版本了？

**Comment by jqctop1** [comment]
这个我们已经更新apktool了
