### ISSUE TITLE
app启动后StackOverFlowError

### ISSUE THREAD

**Issue by seaskyzth** [Tencent/matrix#237]
异常类型：app 运行时异常

手机型号：一加3

手机系统版本：Android 8.0

matrix版本：如: 0.5.1

gradle版本：如: 3.1.2

问题描述：启动app后直接报StackOverFlowError错误，无法启动app

堆栈/日志：
2019-05-22 15:52:03.946 7927-7927/com.delelong.dachangcxdr E/AndroidRuntime:     at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.<clinit>(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:0)
        at com.delelong.dachangcxdr.app.DrApp.<init>(DrApp.java:74)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1105)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1090)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:993)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5997)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2019-05-22 15:52:03.947 7927-7927/com.delelong.dachangcxdr E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.delelong.dachangcxdr, PID: 7927
    java.lang.StackOverflowError: stack size 8MB
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)
        at com.tencent.matrix.trace.core.AppMethodBeat.i(Unknown Source:2)

**Comment by buyiyun** [comment]
更新到 0.5.2 试一试

**Comment by seaskyzth** [comment]
> 
> 
> 更新到 0.5.2 试一试
更新到0.5.2后有新的问题，同样是启动后，找不到so文件，我的项目ndk过滤只有armeabi：
05-23 11:44:12.098 14456-14521/com.delelong.dachangcxdr E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-2
    Process: com.delelong.dachangcxdr, PID: 14456
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:833)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.delelong.dachangcxdr-2/base.apk"],nativeLibraryDirectories=[/data/app/com.delelong.dachangcxdr-2/lib/arm, /data/app/com.delelong.dachangcxdr-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]] couldn't find "libio-canary.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:379)
        at java.lang.System.loadLibrary(System.java:1086)
        at com.tencent.matrix.iocanary.core.IOCanaryJniBridge.loadJni(IOCanaryJniBridge.java:95)
        at com.tencent.matrix.iocanary.core.IOCanaryJniBridge.install(IOCanaryJniBridge.java:43)
        at com.tencent.matrix.iocanary.core.IOCanaryCore.initDetectorsAndHookers(IOCanaryCore.java:83)
        at com.tencent.matrix.iocanary.core.IOCanaryCore.start(IOCanaryCore.java:49)
        at com.tencent.matrix.iocanary.IOCanaryPlugin.start(IOCanaryPlugin.java:62)
        at com.delelong.dachangcxdr.app.DrApp.initTecentMatrix(DrApp.java:366)
        at com.delelong.dachangcxdr.app.DrApp.access$500(DrApp.java:74)
        at com.delelong.dachangcxdr.app.DrApp$2.call(DrApp.java:126)
        at com.delelong.dachangcxdr.app.DrApp$2.call(DrApp.java:110)
        at rx.Observable.unsafeSubscribe(Observable.java:8460)
        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:833)

**Comment by hehonghui** [comment]
遇到同样的问题，测试设备为 Nexus 6, 原生的 Android 7.1 系统 ~ 感叹，Matrix 居然是这个质量~

**Comment by buyiyun** [comment]
针对找不到 so 的问题  可以参考 sample 的做法 在build.gradle
 defaultConfig {
        applicationId "sample.tencent.matrix"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
        }
    }

**Comment by iFarSeer** [comment]
同样遇到此问题，华为 JKM-AL00 8.10系统。

**Comment by yinyinnie** [comment]
感叹：Matrix竟然是这个质量，启动就StackOverflow

**Comment by paozhuanyinyu** [comment]
> 感叹：Matrix竟然是这个质量，启动就StackOverflow

医者不能自医啊呀

**Comment by MichaelJokAr** [comment]
遇到同样的问题，9.0模拟器

**Comment by MichaelJokAr** [comment]
更新到了0.5.2好了
