### ISSUE TITLE
启动崩溃:Out-of-order method_idx for annotation

### ISSUE THREAD

**Issue by logwee** [Tencent/matrix#287]
```
异常类型：app 运行时异常

手机型号：vivo x21

手机系统版本：8.1

matrix版本：0.5.2

gradle版本：3.1.0

问题描述：启动崩溃，关闭trace代码生成后运行正常

堆栈/日志：
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.demo.demo.BaseApplication" on path: DexPathList[[zip file "/data/app/com.demo.demo-dtDvC1Y1HWtEd5OIWeE3CQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.demo-dtDvC1Y1HWtEd5OIWeE3CQ==/lib/arm, /data/app/com.dysdk.dycore-dtDvC1Y1HWtEd5OIWeE3CQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1093)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:991)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6115) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1921) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6949) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.dysdk.dycore-dtDvC1Y1HWtEd5OIWeE3CQ==/base.apk because: Failure to verify dex file '/data/app/com.demo.demo-dtDvC1Y1HWtEd5OIWeE3CQ==/base.apk': Out-of-order method_idx for annotation: 83ec then 83ec
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)

**Comment by logwee** [comment]
这个问题没有其他人遇到吗

**Comment by super-h-c** [comment]
遇到过请问解决了吗

**Comment by RabbitFeng** [comment]
2022-07-13 11:48:30.504 18476-18476/com.noxgroup.app.booster E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.noxgroup.app.booster:nbads, PID: 18476
    java.lang.RuntimeException: Unable to get provider com.applovin.sdk.AppLovinInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.applovin.sdk.AppLovinInitProvider" on path: DexPathList[[zip file "/data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/base.apk"],nativeLibraryDirectories=[/data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/lib/x86, /data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.applovin.sdk.AppLovinInitProvider" on path: DexPathList[[zip file "/data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/base.apk"],nativeLibraryDirectories=[/data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/lib/x86, /data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6972)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by RabbitFeng** [comment]
同样的问题，打包出来会丢失某些类文件：
2022-07-13 11:48:30.504 18476-18476/com.noxgroup.app.booster E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.noxgroup.app.booster:nbads, PID: 18476
    java.lang.RuntimeException: Unable to get provider com.applovin.sdk.AppLovinInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.applovin.sdk.AppLovinInitProvider" on path: DexPathList[[zip file "/data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/base.apk"],nativeLibraryDirectories=[/data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/lib/x86, /data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.applovin.sdk.AppLovinInitProvider" on path: DexPathList[[zip file "/data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/base.apk"],nativeLibraryDirectories=[/data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/lib/x86, /data/app/com.noxgroup.app.booster-Gv5vUkv2JA1x8FD8lden1w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6972)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
