### ISSUE TITLE
集成0.5.2后，启动应用一会就崩溃了

### ISSUE THREAD

**Issue by Justever** [Tencent/matrix#289]
异常类型：运行后随意点击滑动页面大几率崩溃

手机型号：三星S9

手机系统版本：Android 9.0

matrix版本：0.5.2

gradle版本：3.0.1

问题描述：

E/AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.tjoy.App.Aggregation.Loan.Activity.LoadMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.GapWorker.remove(android.support.v7.widget.RecyclerView)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4682)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4700)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.GapWorker.remove(android.support.v7.widget.RecyclerView)' on a null object reference
        at android.support.v7.widget.RecyclerView.onDetachedFromWindow(RecyclerView.java:2621)
        at android.view.View.dispatchDetachedFromWindow(View.java:20047)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3983)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3975)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3975)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3975)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5576)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5547)
        at android.view.ViewGroup.removeView(ViewGroup.java:5478)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1520)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3218)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:262)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:362)
        at com.tjoy.tjoybaselib.ui.activity.BaseAssembledAct.onDestroy(BaseAssembledAct.java:83)
        at com.tjoy.tjoycloud.App.Aggregation.Loan.Activity.LoadMainActivity.onDestroy(LoadMainActivity.java:76)
        at android.app.Activity.performDestroy(Activity.java:7680)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4667)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4700) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6981) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by txfelixzhou** [comment]
还出现么，找到S9的机器没法重现
