### ISSUE TITLE
ResourcePlugin的疑问

### ISSUE THREAD

**Issue by hwt83525055** [Tencent/matrix#33]
## Issue /提问须知

```
异常类型：app 运行时异常

手机型号：小米8

手机系统版本：9.0

matrix版本：0.4.8

gradle版本： 3.2.1

问题描述： 
     创建内部类Handler的内存泄漏 Resourceplugin没有任何的回调，sampleApp中的static activity 则会正常提示

**Comment by tomystang** [comment]
试试post一个延时比较长，比方说1h的message到你的内部handler里？

如果你只是创建一个handler内部类的话实际上还是不会导致Activity泄漏的。

**Comment by hwt83525055** [comment]
每10S循环post的 Runnable

**Comment by wuzhiqian** [comment]
异常类型：app 运行时异常

手机系统版本：9.0 虚拟机

matrix版本：0.4.10

gradle版本： 3.2.1 

finish activity时出现以下错误。怀疑跟ResourcePlugin.activityLeakFixer方法有关
 java.lang.RuntimeException: Unable to destroy activity {com.xxx.xxx/com.xxx.xxx.ui.CActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setAlpha(int)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4458)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4476)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setAlpha(int)' on a null object reference
        at android.support.v4.widget.SwipeRefreshLayout.setColorViewAlpha(SwipeRefreshLayout.java:234)
        at android.support.v4.widget.SwipeRefreshLayout.reset(SwipeRefreshLayout.java:209)
        at android.support.v4.widget.SwipeRefreshLayout.onDetachedFromWindow(SwipeRefreshLayout.java:230)
        at android.view.View.dispatchDetachedFromWindow(View.java:18400)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5359)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5330)
        at android.view.ViewGroup.removeView(ViewGroup.java:5261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1550)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3260)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:274)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:419)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:210)
        at me.yokeyword.fragmentation.SupportActivity.onDestroy(SupportActivity.java:51)

**Comment by SZn007** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setAlpha(int)' on a null object reference
        at android.support.v4.widget.SwipeRefreshLayout.setColorViewAlpha(SwipeRefreshLayout.java:227)
        at android.support.v4.widget.SwipeRefreshLayout.reset(SwipeRefreshLayout.java:202)
        at android.support.v4.widget.SwipeRefreshLayout.onDetachedFromWindow(SwipeRefreshLayout.java:223)
        at android.view.View.dispatchDetachedFromWindow(View.java:15589)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3189)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4717)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4691)
        at android.view.ViewGroup.removeView(ViewGroup.java:4622)
        at android.support.v4.view.ViewPager.removeView(ViewPager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1529)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroyView(FragmentManager.java:3229)
        at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2561)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1512)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3235)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:265)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
        at com.ss.android.tuchong.common.base.BaseActivity.onDestroy(BaseActivity.java:271)
        at android.app.Activity.performDestroy(Activity.java:7079)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4280)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4311) 
        at android.app.ActivityThread.-wrap6(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6238) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by SZn007** [comment]
应该与ResourcePlugin.activityLeakFixer(this)中view.setBackgroundDrawable(null);有关，直接将View中的mBackground设为null，SwipeRefreshLayout中onDetachedFromWindow()调用了reset()方法，mCircleView.getBackground().setAlpha(targetAlpha);，就空指针了。

**Comment by SZn007** [comment]
是不是应该通过post来实现，让系统的onDestroy()调用完成后，再执行。

**Comment by wuzq123** [comment]
> 应该与ResourcePlugin.activityLeakFixer(this)中view.setBackgroundDrawable(null);有关，直接将View中的mBackground设为null，SwipeRefreshLayout中onDetachedFromWindow()调用了reset()方法，mCircleView.getBackground().setAlpha(targetAlpha);，就空指针了。

是的
