### ISSUE TITLE
编译报错 :app:transformClassesWithDexBuilderForDebug

### ISSUE THREAD

**Issue by wjxfhxy** [Tencent/matrix#330]
异常类型：编译异常

matrix版本：如: 0.6.0

gradle版本：如: 5.1.1

问题描述：工程引入Matrix后，对原工程中的业务代码修改病编译，编译出现如题的错误

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
    .......................
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.io.FileNotFoundException: F:\Demo\DemoApp\app\build\outputs\traceClassOut\debug\annotations-4.9.0_09d351870d810f59685b2ce781e8fcd3e2f9e2fe.jar
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	.......................

貌似说文件找不到

**Comment by feer921** [comment]
是啊，接入后，每次 运行项目都报错，然后必须clean一下才行

**Comment by feer921** [comment]
app\build\outputs\traceClassOut\ddkt\debug\25_0b884e24efe752700d8c843b0c0d4ef978c15b14.jar
每次运行项目，老报这个编译异常，能解决一下吗？

**Comment by feer921** [comment]
@changelcai

**Comment by alen252** [comment]
遇到同样的问题

**Comment by alen252** [comment]
@changelcai

**Comment by yuxinfeng** [comment]
@changelcai 解决了吗

**Comment by XanderWang** [comment]
windows 环境编译有这个问题，难道只有 window 才会遇到？

**Comment by mrkyee** [comment]
+1
