### ISSUE TITLE
ApkChecker 代码健壮性BUG

### ISSUE THREAD

**Issue by hfutgl** [Tencent/matrix#35]
java.io.IOException: Unable to delete file: E:\Work\recompile\.\apks\XXAPK\XXAPK_unzip\lib\arm64-v8a\libxxx.so
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
unzip目录是工具自己创建

**Comment by jqctop1** [comment]
java -jar matrix-apk-canary-0.4.10.jar --apk .\apks\XXX\XXX.apk --format mm.html -manifest -fileSize -countMethod --group GROUP-BY package -duplicatedFile -checkResProguard -checkMultiLibrary -unusedAssets -countR -uncompressedFile -findNonAlphaPng

GROUP-BY 不用加到命令里面去

第一个问题以及nullpointer我再看下
