### ISSUE TITLE
项目用了GSON2.8.6，再用matrix插件打包，运行时，会NoClassDefFoundError崩溃

### ISSUE THREAD

**Issue by vitotang1** [Tencent/matrix#382]
异常类型：app 运行时异常

手机型号：所有手机

手机系统版本：所有版本

matrix版本：0.6.0

gradle版本：3.1.4

问题描述：android上，项目用了gson2.8.6，再用matrix插件打包，运行时，会NoClassDefFoundError崩溃。项目如果用gson2.8.5则正常。

堆栈/日志：
2019-10-14 20:08:37.284 31739-31739/sample.tencent.matrix E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sample.tencent.matrix, PID: 31739
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/Gson;
        at sample.tencent.matrix.MainActivity.onResume(MainActivity.java:43)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
        at android.app.Activity.performResume(Activity.java:7318)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3891)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3071)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1767)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:7015)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.Gson" on path: DexPathList[[zip file "/data/app/sample.tencent.matrix-l5JfzfBOyKOGfya2p3JHWw==/base.apk"],nativeLibraryDirectories=[/data/app/sample.tencent.matrix-l5JfzfBOyKOGfya2p3JHWw==/lib/arm, /data/app/sample.tencent.matrix-l5JfzfBOyKOGfya2p3JHWw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

**Comment by wancong3** [comment]
没错，2.8.6版本在安卓上有重大bug，给大家排一下雷。

**Comment by Carlos2927** [comment]
什么问题导致的 我也碰到了

**Comment by kirin521** [comment]
楼主解决了吗？我也遇到了。。

**Comment by Eren-Shen** [comment]
同樣的問題，有人解決了嗎？

**Comment by SepBreUp** [comment]
2.8.7也不行，问题有解决办法吗

**Comment by SepBreUp** [comment]
有找到解决办法吗，同样打包显示ClassNotFoundException，但是解包实际打包进去了

**Comment by JackFung2015** [comment]
按照demo改成2.7版本可以

**Comment by kirin521** [comment]
这个啥时候能解决。。

**Comment by AceInAndroid** [comment]
升级到GSON最新版本可以解决 https://github.com/google/gson/releases

**Comment by huangShan-gitHub** [comment]
和楼主问题一样，降级就好了，也是2.8.6的坑。
