### ISSUE TITLE
关闭FPS，TraceConfig的enableFPS传false的时候检测到慢函数问题会崩溃

### ISSUE THREAD

**Issue by alen252** [Tencent/matrix#416]
异常类型：app 运行时异常/编译异常

手机型号：如: 荣耀V10

手机系统版本：如:Android 9.0 (如是编译异常，则可以不填)

matrix版本：如: 0.6.0

gradle版本：如: 3.0.0

问题描述：关闭FPS，TraceConfig的enableFPS传false的时候检测到慢函数问题会崩溃

堆栈/日志：
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
        at com.tencent.matrix.trace.tracer.EvilMethodTracer.dispatchEnd(EvilMethodTracer.java:86)
        at com.tencent.matrix.trace.core.UIThreadMonitor.dispatchEnd(UIThreadMonitor.java:273)
        at com.tencent.matrix.trace.core.UIThreadMonitor.access$200(UIThreadMonitor.java:17)
        at com.tencent.matrix.trace.core.UIThreadMonitor$1.dispatchEnd(UIThreadMonitor.java:110)
        at com.tencent.matrix.trace.core.LooperMonitor.dispatch(LooperMonitor.java:123)
        at com.tencent.matrix.trace.core.LooperMonitor.access$000(LooperMonitor.java:14)
        at com.tencent.matrix.trace.core.LooperMonitor$1.println(LooperMonitor.java:87)
        at android.os.Looper.loop(Looper.java:252)
```

**Comment by LinXiaoTao** [comment]
一样的问题 #451
