### ISSUE TITLE
[Matrix.ApkJob]Task executor execute with error:com.tencent.matrix.apk.model.exception.TaskExecuteException

### ISSUE THREAD

**Issue by ronindong** [Tencent/matrix#429]
[ERROR][Matrix.ApkJob]Task executor execute with error:com.tencent.matrix.apk.model.exception.TaskExecuteException: Caught exception during read:
java.util.concurrent.ExecutionException: com.tencent.matrix.apk.model.exception.TaskExecuteException: Caught exception during read:
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:509)
	at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:482)
	at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
	at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)
Caused by: com.tencent.matrix.apk.model.exception.TaskExecuteException: Caught exception during read:
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:162)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:51)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.imageio.IIOException: Caught exception during read:
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1817)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:99)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:96)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:96)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:129)
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1308)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1360)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1493)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1810)
	... 11 more

**Comment by xushihao** [comment]
[ERROR][Matrix.ApkJob]Task executor execute with error:com.tencent.matrix.apk.model.exception.TaskExecuteException
java.util.concurrent.ExecutionException: com.tencent.matrix.apk.model.exception.TaskExecuteException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:501)
	at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:474)
	at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
	at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)
Caused by: com.tencent.matrix.apk.model.exception.TaskExecuteException
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:162)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:100)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:96)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:96)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:129)
	... 5 more

**Comment by moumou0000** [comment]
遇到了同样的问题，在线等这个问题的处理方式 @changelcai

**Comment by pioneerz** [comment]
遇到的同样的问题+1

**Comment by xueqiya** [comment]
遇到的同样的问题+1

**Comment by gaoxuu** [comment]
https://bugs.openjdk.org/browse/JDK-8211795 升级 Java 版本就可以了
