### ISSUE TITLE
项目开启混淆后编译异常

### ISSUE THREAD

**Issue by forEveryDay** [Tencent/matrix#458]
异常类型：app 编译异常

matrix版本：0.6.5

gradle版本：5.1.1

问题描述：开启混淆后编译异常，如果不开启混淆，则可以正常编译并且生产methodMapping.txt文件

堆栈/日志：
`Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.tencent.matrix.trace.retrace.MappingCollector.processClassMapping(MappingCollector.java:43)
	at com.tencent.matrix.trace.retrace.MappingReader.parseClassMapping(MappingReader.java:102)
	at com.tencent.matrix.trace.retrace.MappingReader.read(MappingReader.java:61)
	at com.tencent.matrix.trace.transform.MatrixTraceTransform$ParseMappingTask.run(MatrixTraceTransform.java:246)`

**Comment by forEveryDay** [comment]
这里是否判空一下会好一些，当然不排除是我项目的混淆规则导致出现了异常类，但是由于项目集成的包太多，太难排查了
`  @Override
    public boolean processClassMapping(String className, String newClassName) {
        this.mObfuscatedRawClassMap.put(newClassName, className);
        this.mRawObfuscatedClassMap.put(className, newClassName);
        this.mRawObfuscatedPackageMap.put(className.substring(0, className.lastIndexOf('.')), newClassName.substring(0, newClassName.lastIndexOf('.')));
        return true;
    }`

**Comment by forEveryDay** [comment]
最后排查出，我项目中如果添加高级混淆方法：
`# 把执行后的类重新放在某一个目录下，后跟一个目录名
-repackageclasses ''`
开启混淆后编译会报如上错误

**Comment by soonmay** [comment]
我这边同样遇到了

**Comment by Raynor999** [comment]
> 最后排查出，我项目中如果添加高级混淆方法：
> `-repackageclasses`
> 开启混淆后编译会报如上错误

去掉这个混淆后，release 版本可以正常生成 methodMapping.txt 文件吗？

**Comment by forEveryDay** [comment]
> > 最后排查出，我项目中如果添加高级混淆方法：
> > `-repackageclasses`
> > 开启混淆后编译会报如上错误
> 
> 去掉这个混淆后，release 版本可以正常生成 methodMapping.txt 文件吗？ 我这边去掉也还是不能生成

这两个貌似也有影响，但我不确定。
android.enableD8=false
android.enableR8=false
