### ISSUE TITLE
添加matrix-plugin后，app运行时崩溃

### ISSUE THREAD

**Issue by kakayang2011** [Tencent/matrix#46]
在将matrix-plugin添加到app运行后，app会崩溃。
stackrace如下：
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/kid//UserInfo$Info;
	at com.android.kid.UserInfoManager$2.doInBackground(UserInfoManager.java:234)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.kid.UserInfo$Info" on path: DexPathList[[zip file "/data/app/com.android.kid-mRwOdZgEI_UabtsV4LmFvw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.kid-mRwOdZgEI_UabtsV4LmFvw==/lib/arm, /system/fake-libs, /data/app/com.android.kid-mRwOdZgEI_UabtsV4LmFvw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 6 more
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/protobuf/GeneratedMessage;
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:282)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
		at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677)
		at dalvik.system.DexPathList.findClass(DexPathList.java:466)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:91)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.bytedance.frameworks.plugin.core.DelegateClassLoader.findClass(DelegateClassLoader.java:62)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
		... 7 more
	Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.protobuf.GeneratedMessage" on path: DexPathList[[zip file "/data/app/com.android.kid
-mRwOdZgEI_UabtsV4LmFvw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.kid
-mRwOdZgEI_UabtsV4LmFvw==/lib/arm, /system/fake-libs, /data/app/com.android.kid-mRwOdZgEI_UabtsV4LmFvw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
		... 17 more

**Comment by txfelixzhou** [comment]
从日志上看，提示是protobuf中找不到类定义（com.android.kid.UserInfo$Info），而matrix并未使用，建议查一下app代码。另外，使用matrix的部分，可以参考sample-android和readme中的使用说明

**Comment by kakayang2011** [comment]
但是我在把traceCanary设为disable后 是可以找到的。感觉是因为TraceTransform引起的

**Comment by kakayang2011** [comment]
是这样设置的。
我在blackMethodList.txt文件中 设置了 
  [package]
-keeppackage com/ss/android/uniqueid

在Debug.methodmap中就没有相关的信息了。但是仍然出现这样的异常～

**Comment by kakayang2011** [comment]
编译过程中有一个报错信息
[ERROR][Matrix.MethodTracer][traceMethodFromJar] err! /Users/kaka/work/app/build/matrix_output/classes/MatrixTraceTransform/275_d9f457d7c2fed02c49b3ac30c8cc65a002d4d424.jar

**Comment by changelcai** [comment]
嗯好，看起来是解压这个jar出现异常，导致最后没打包进apk，我解决下，兼容下这种异常情况。感谢反馈～
