### ISSUE TITLE
apkchecker0.6.0编译Task executor execute with error:null问题

### ISSUE THREAD

**Issue by LtlittleBrother** [Tencent/matrix#472]
异常类型：编译异常
matrix版本：0.6.0
gradle版本：5.0

问题描述：apkchecker0.6.0编译一直报“Task executor execute with error:null”

堆栈/日志：
[ERROR][Matrix.ApkJob]Task executor execute with error:null
java.util.concurrent.CancellationException
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:509)
        at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:482)
        at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
        at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)

**Comment by eggbrid** [comment]
解决了吗？

**Comment by Lyongwang** [comment]
matrix-apk-canary-0.6.6.jar
还是会有这个问题
堆栈日志：
[ERROR][Matrix.ApkJob]Task executor execute with error:null
java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:509)
	at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:482)
	at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
	at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)

**Comment by Charon1997** [comment]
去掉unstrippedSo 这个task可以解决这个问题

**Comment by tsutsuku** [comment]
我在2.1.0版本使用高版本ndk的llvm-nm时会在unstrippedSo抛Task executor execute with error:null。
将nm替换为低版本ndk中arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-nm.exe 就能正常工作了

**Comment by Charon1997** [comment]
hi，我已经收到你的邮件了，我会尽快查看的~
