### ISSUE TITLE
AppBeatMethod ANR

### ISSUE THREAD

**Issue by diehell02** [Tencent/matrix#477]
异常类型：ANR

系统版本：如:Android 9.0

matrix版本：如: 0.6.5

gradle版本：如: 5.4.1

问题描述：在应用正常测试过程中，发生了ANR现象 

堆栈/日志：

group="main" sCount=1 dsCount=0 flags=1 obj=0x73a81d90 self=0x75000e0a00
--
sysTid=18078 nice=-10 cgrp=default sched=0/0 handle=0x75851009a0
state=S schedstat=( 2975223611772 937936488453 6078846 ) utm=236642 stm=60879 core=1 HZ=100
stack=0x7ff7909000-0x7ff790b000 stackSize=8MB
held mutexes=at com.tencent.matrix.trace.core.AppMethodBeat.dispatchBegin(AppMethodBeat.java:187)waiting to lock <0x04b1f5ba> (a java.lang.Object)at com.tencent.matrix.trace.core.AppMethodBeat.access$100(AppMethodBeat.java:20)at com.tencent.matrix.trace.core.AppMethodBeat$1.dispatchStart(AppMethodBeat.java:64)at com.tencent.matrix.trace.core.LooperMonitor$LooperDispatchListener.onDispatchStart(LooperMonitor.java:42)at com.tencent.matrix.trace.core.LooperMonitor.dispatch(LooperMonitor.java:209)at com.tencent.matrix.trace.core.LooperMonitor.access$000(LooperMonitor.java:17)at com.tencent.matrix.trace.core.LooperMonitor$LooperPrinter.println(LooperMonitor.java:196)at android.os.Looper.loop(Looper.java:151)at android.app.ActivityThread.main(ActivityThread.java:6518)at java.lang.reflect.Method.invoke(Native method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

————————————————————————————————————————————

有参考过[#342](#342 )，但是我这边的代码只是简单的实现了DefaultPluginListener，并没有特殊的操作。而且如果是代码问题应该也不会是偶现的现象。
希望能得到解答。

**Comment by vitotang1** [comment]
有解决吗

**Comment by smalldayday** [comment]
有解决吗？
