### ISSUE TITLE
使用ApkChecker出现无法解析XML错误   Could not decode XML

### ISSUE THREAD

**Issue by PeterXiaosa** [Tencent/matrix#487]
您好！
我在接入ApkChecker的时候，调用 `java -jar matrix-apk-canary-0.6.5.jar --config 我的本地路径/config.json` 想生成Apk分析结果。但是出现了如下错误：
```
[INFO][Matrix.ApkJob]format list [mm.html, mm.json]
[INFO][Matrix.UnZipTask]inputPath:D:/Open_Project/matrix_origin/EstarAndroid.apk
[INFO][Matrix.UnZipTask]outputPath:D:/Open_Project/matrix_origin/result
[INFO][Matrix.ManifestAnalyzeTask]inputPath:D:/Open_Project/matrix_origin/result
[INFO][Matrix.ShowFileSizeTask]inputPath:D:/Open_Project/matrix_origin/result
[INFO][Matrix.MethodCountTask]input path:D:/Open_Project/matrix_origin/result
[INFO][Matrix.ResProguardCheckTask]inputPath:D:/Open_Project/matrix_origin/result
[INFO][Matrix.MultiLibCheckTask]inputPath:D:/Open_Project/matrix_origin/result
[INFO][Matrix.UnusedAssetsTask]ignore assets 1
[INFO][Matrix.ResProguardCheckTask]directory anim has a non-proguard name!
[INFO][Matrix.UnusedResourcesTask]find resource declarations 13534 items.
[INFO][Matrix.UnusedResourcesTask]find resource references in classes: 981 items.
[ERROR][Matrix.ApkResourceDecoder]Parse xml error,Expected: 0x00080003 or 0x00080001, got: 0x6d783f3c
[INFO][Matrix.UnusedAssetsTask]find all assets count: 22
[INFO][Matrix.UnusedAssetsTask]find reference assets count: 2
[ERROR][Matrix.ApkJob]Task executor execute with error:com.tencent.matrix.apk.model.exception.TaskExecuteException: Could not decode XML,end tag name </p> must match start tag name <string> from line 3594 (position: TEXT seen ...</span></span> </p>... @3594:293)
java.util.concurrent.ExecutionException: com.tencent.matrix.apk.model.exception.TaskExecuteException: Could not decode XML,end tag name </p> must match start tag name <string> from line 3594 (position: TEXT seen ...</span></span> </p>... @3594:293)
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:509)
        at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:482)
        at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
        at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)
Caused by: com.tencent.matrix.apk.model.exception.TaskExecuteException: Could not decode XML,end tag name </p> must match start tag name <string> from line 3594 (position: TEXT seen ...</span></span> </p>... @3594:293)
        at com.tencent.matrix.apk.model.task.UnusedResourcesTask.call(UnusedResourcesTask.java:479)
        at com.tencent.matrix.apk.model.task.UnusedResourcesTask.call(UnusedResourcesTask.java:61)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: brut.androlib.AndrolibException: Could not decode XML,end tag name </p> must match start tag name <string> from line 3594 (position: TEXT seen ...</span></span> </p>... @3594:293)
        at com.tencent.matrix.apk.model.task.util.XmlPullResourceRefDecoder.decode(XmlPullResourceRefDecoder.java:69)
        at com.tencent.matrix.apk.model.task.util.ApkResourceDecoder.decodeResValues(ApkResourceDecoder.java:213)
        at com.tencent.matrix.apk.model.task.util.ApkResourceDecoder.decodeResourcesRef(ApkResourceDecoder.java:241)
        at com.tencent.matrix.apk.model.task.UnusedResourcesTask.decodeResources(UnusedResourcesTask.java:380)
        at com.tencent.matrix.apk.model.task.UnusedResourcesTask.call(UnusedResourcesTask.java:465)
        ... 5 more
Caused by: org.xmlpull.v1.XmlPullParserException: end tag name </p> must match start tag name <string> from line 3594 (position: TEXT seen ...</span></span> </p>... @3594:293)
        at org.xmlpull.mxp1.MXParser.parseEndTag(MXParser.java:1689)
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1131)
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
        at com.tencent.matrix.apk.model.task.util.XmlPullResourceRefDecoder.decode(XmlPullResourceRefDecoder.java:64)
        ... 9 more
```

看错误日志是知道XML文件格式不对，但是光看Log并不知道是哪里出了问题，不知道从何处开始去排查问题，想请问下应该从哪里去寻找切入点解决这个问题呢？谢谢~

**Comment by PeterXiaosa** [comment]
在 [这个Issue](https://github.com/Tencent/matrix/issues/149)中这位大哥也碰到了好像类似的问题，但是issue被关闭了，不知道是如何解决的，希望能赐教

**Comment by TangHuaiZhe** [comment]
全局搜`</p>`  ？
` </p> must match start tag name <string> from line 3594`
找到那个行数超过3600行的文件试试？

**Comment by PeterXiaosa** [comment]
十分感谢 我太蠢了 看到了`</p>`  但是没想到去全局搜包含这个字符的xml文件，光想着会像编译时报错一样日志中会定位到哪个文件哪里出了问题。进了思维定式。  
现在打出来了分析结果。不过不是3594行，感觉它这个line 3594应该不是xml中的行数。我xml只有三百多行。

**Comment by geekzxiang** [comment]
这个能输出文件位置就好了，有的项目代码属实不好找
