### ISSUE TITLE
按文档集成后，打开app崩溃 ，can't find  "libio-canary.so" 

### ISSUE THREAD

**Issue by fangyeren** [Tencent/matrix#499]
异常类型：app 运行时异常

手机型号：xiaomi note2 

手机系统版本：Android 8.0

matrix版本：如: 0.6.5

gradle版本：如: 5.4.1

问题描述：集成编译没有问题，打包后，点击app启动时崩溃，崩溃日志如下，

堆栈/日志：
UncaughtException detected: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ekwing.students-6iYTgnpGb4ks5Q1ezzSLzg==/base.apk"],nativeLibraryDirectories=[/data/app/com.ekwing.students-6iYTgnpGb4ks5Q1ezzSLzg==/lib/arm, /data/app/com.ekwing.students-6iYTgnpGb4ks5Q1ezzSLzg==/base.apk!/lib/armeabi, /system/lib, /system/vendor/lib]]] couldn't find "libio-canary.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.tencent.matrix.iocanary.core.IOCanaryJniBridge.loadJni(IOCanaryJniBridge.java:95)
        at com.tencent.matrix.iocanary.core.IOCanaryJniBridge.install(IOCanaryJniBridge.java:43)
        at com.tencent.matrix.iocanary.core.IOCanaryCore.initDetectorsAndHookers(IOCanaryCore.java:83)
        at com.tencent.matrix.iocanary.core.IOCanaryCore.start(IOCanaryCore.java:49)
        at com.tencent.matrix.iocanary.IOCanaryPlugin.start(IOCanaryPlugin.java:62)
        at com.ekwing.business.application.GlobalApplication.onCreate(GlobalApplication.java:110)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by fangyeren** [comment]
armeabi-v7a 添加它后，就没有问题了

**Comment by BlissYang91** [comment]
没有用
