### ISSUE TITLE
缺少arm64-v8a so库

### ISSUE THREAD

**Issue by careyc** [Tencent/matrix#50]
```
异常类型：app 运行时异常

手机系统版本：Android 9

Android Studio版本：3.2.1
NDK 版本：18.1

matrix版本：0.4.10

gradle版本：4.4

问题描述：缺少arm64-v8a so库，couldn't find "libSqliteLint-lib.so"

E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/***-EceQZsEfONFxYG1zekFRSA==/***.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libSqliteLint-lib.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.tencent.sqlitelint.SQLiteLintNativeBridge.loadLibrary(SQLiteLintNativeBridge.java:37)
        at com.tencent.sqlitelint.SQLiteLint.<clinit>(SQLiteLint.java:38)

**Comment by txfelixzhou** [comment]
问题已知，除了arm64-v8a, 还有 x86-64， 是真机吗，什么机型呢？

**Comment by txfelixzhou** [comment]
已经修复，在编包测试验证，稍等

**Comment by txfelixzhou** [comment]
已提交 [Bugfix: SQLiteLint Support "arm64-v8a", "x86_64”.  issue#50]（https://github.com/Tencent/matrix/commit/d834a83154c0341b9752efd02c4f8e0874fe9811）

**Comment by gengjiawen** [comment]
这个大概什么时候merge到master？

**Comment by txfelixzhou** [comment]
已合入
