### ISSUE TITLE
release 签名打包后初始化即崩溃

### ISSUE THREAD

**Issue by lynnzc** [Tencent/matrix#67]
```
异常类型：release 签名打包后初始化即崩溃

手机型号：

手机系统版本：Android P & O

matrix版本：0.4.10

gradle版本：4.6

问题描述：如：在 android P 出现系统不兼容 
主要错误在
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.matrix.trace.core.MethodBeat" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.borderxlab.bieyang-e1JvNLkCAI0N7Gs1fyhJaQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.borderxlab.bieyang-e1JvNLkCAI0N7Gs1fyhJaQ==/lib/x86, /data/app/com.borderxlab.bieyang-e1JvNLkCAI0N7Gs1fyhJaQ==/base.apk!/lib/x86, /system/lib]]


详细错误日志：
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/matrix/trace/core/MethodBeat;
        at com.crashlytics.android.CrashlyticsInitProvider.onCreate(Unknown Source:2)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.matrix.trace.core.MethodBeat" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.borderxlab.bieyang-e1JvNLkCAI0N7Gs1fyhJaQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.borderxlab.bieyang-e1JvNLkCAI0N7Gs1fyhJaQ==/lib/x86, /data/app/com.borderxlab.bieyang-e1JvNLkCAI0N7Gs1fyhJaQ==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.crashlytics.android.CrashlyticsInitProvider.onCreate(Unknown Source:2) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1917) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1892) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-01-04 10:39:34.043 1716-1788/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2019-01-04 10:39:34.203 2541-4297/com.google.android.apps.nexuslauncher E/s.nexuslaunche: No package ID ff found for ID 0xffffffff.
2019-01-04 10:39:34.203 2541-4297/com.google.android.apps.nexuslauncher E/IconLoader: Could not find icon drawable from resource
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
        at android.content.res.Resources.getDrawable(Resources.java:827)
        at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(SourceFile:118)
        at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(SourceFile:94)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(SourceFile:325)
        at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(SourceFile:188)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(SourceFile:173)
        at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(SourceFile:214)
        at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(SourceFile:80)
        at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
        at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by changelcai** [comment]
跟手机系统版本有关系？
