### ISSUE TITLE
error:com.tencent.matrix.apk.model.exception.TaskExecuteException

### ISSUE THREAD

**Issue by pioneerz** [Tencent/matrix#680]
[E][Matrix.ApkJob] Task executor execute with error:com.tencent.matrix.apk.model.exception.TaskExecuteException: Caught exception during read: 
java.util.concurrent.ExecutionException: com.tencent.matrix.apk.model.exception.TaskExecuteException: Caught exception during read: 
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:526)
	at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:499)
	at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
	at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)
Caused by: com.tencent.matrix.apk.model.exception.TaskExecuteException: Caught exception during read: 
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:162)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:51)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.imageio.IIOException: Caught exception during read: 
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1820)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:99)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:96)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.findNonAlphaPng(FindNonAlphaPngTask.java:96)
	at com.tencent.matrix.apk.model.task.FindNonAlphaPngTask.call(FindNonAlphaPngTask.java:129)
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1311)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1363)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1496)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1813)
	... 11 more

请问这个问题怎么解决

**Comment by gaoxuu** [comment]
https://bugs.openjdk.org/browse/JDK-8211795  升级 Java 版本就可以了
