### ISSUE TITLE
Matrix 升级到androidx之后开启混淆打出来的apk size变小了 dex出现丢失

### ISSUE THREAD

**Issue by Avengong** [Tencent/matrix#686]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```
异常类型：开启混淆后，打出的apk包缺少dex文件

手机型号：无

手机系统版本：无

matrix版本： 2.0.2

gradle版本：4.1.0

问题描述：不开混淆没有问题。开启混淆后，部分dex文件缺失了，导致apk包小了近一半，无法运行。

堆栈/日志：
1. 如是编译异常，请在执行 gradle 命令时，加上 --stacktrace;
2. 日志我们需要过滤" Matrix. "关键字;

打包流程没问题，不确定你们需要哪些日志？？

```

**Comment by scuzoutao** [comment]
+1

**Comment by Andyload** [comment]
@Avengong 可以安装不能运行？

**Comment by Avengong** [comment]
> 

是的，我demo的apk有部分dex，可以安装无法运行。项目打出的正式包没有dex，无法安装。

**Comment by scuzoutao** [comment]
> ，我demo的apk有部分dex，可以安装无法运行。项目打出的正式包没有dex，无法安

我的是debug正常，但是release就没有dex

**Comment by Andyload** [comment]
我测试了一下是因为关闭了R8和开了混淆引起，看看工程是不是关闭了R8？

**Comment by scuzoutao** [comment]
> 测试了一下是因为关闭了R8和开了混淆引起，看看工程是不是关闭了R

官方demo打开了R8，编译出来的apk可以安装，但是也打不开。
`2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri: ----- class 'Lcom/tencent/matrix/trace/tracer/SignalAnrTracer;' cl=0x12c55ab0 -----
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:   super='java.lang.Class<com.tencent.matrix.trace.tracer.v>' (cl=0x12c55ab0)
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      0: void com.tencent.matrix.trace.tracer.SignalAnrTracer.h()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      1: void com.tencent.matrix.trace.tracer.SignalAnrTracer.j()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      0: void com.tencent.matrix.trace.tracer.SignalAnrTracer.<clinit>()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      1: void com.tencent.matrix.trace.tracer.SignalAnrTracer.<init>(b.c.a.m.d.c)
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      2: void com.tencent.matrix.trace.tracer.SignalAnrTracer.l()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      3: boolean com.tencent.matrix.trace.tracer.SignalAnrTracer.m()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      4: void com.tencent.matrix.trace.tracer.SignalAnrTracer.n()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      5: void com.tencent.matrix.trace.tracer.SignalAnrTracer.o(java.lang.String, java.lang.String)
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      6: void com.tencent.matrix.trace.tracer.SignalAnrTracer.onANRDumpTrace()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      7: void com.tencent.matrix.trace.tracer.SignalAnrTracer.onANRDumped()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      8: void com.tencent.matrix.trace.tracer.SignalAnrTracer.onPrintTrace()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      9: void com.tencent.matrix.trace.tracer.SignalAnrTracer.p()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:     10: void com.tencent.matrix.trace.tracer.SignalAnrTracer.q()
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:     11: void com.tencent.matrix.trace.tracer.SignalAnrTracer.r(boolean)
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      0: boolean com.tencent.matrix.trace.tracer.SignalAnrTracer.d
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      1: java.lang.String com.tencent.matrix.trace.tracer.SignalAnrTracer.e
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      2: java.lang.String com.tencent.matrix.trace.tracer.SignalAnrTracer.f
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      3: boolean com.tencent.matrix.trace.tracer.SignalAnrTracer.g
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      4: boolean com.tencent.matrix.trace.tracer.SignalAnrTracer.h
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      5: long com.tencent.matrix.trace.tracer.SignalAnrTracer.i
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri:      6: java.lang.String com.tencent.matrix.trace.tracer.SignalAnrTracer.j
2021-12-07 16:15:43.177 27316-27316/? E/.tencent.matri: Failed to register native method com.tencent.matrix.trace.tracer.SignalAnrTracer.nativeInitSignalAnrDetective(Ljava/lang/String;Ljava/lang/String;)V in /data/app/sample.tencent.matrix-DUp_5L6pdFX20IwjCnbqKw==/base.apk
2021-12-07 16:15:43.178 27316-27316/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sample.tencent.matrix, PID: 27316
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/sample.tencent.matrix-DUp_5L6pdFX20IwjCnbqKw==/lib/arm64/libtrace-canary.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.tencent.matrix.trace.tracer.SignalAnrTracer.<clinit>(SignalAnrTracer.java:1)
        at b.c.a.m.a.run(TracePlugin.java:22)
        at b.c.a.m.c.start(TracePlugin.java:7)
        at sample.tencent.matrix.MatrixApplication.onCreate(MatrixApplication.java:58)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7184)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
        at android.app.ActivityThread.access$1600(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2021-12-07 16:15:43.247 904-904/? E/SurfaceFlinger: [Application Error: sample.tencent.matrix#0] rejecting buffer: bufWidth=1452, bufHeight=751, front.active_legacy.{w=1452, h=688}
2021-12-07 16:15:43.513 904-904/? E/Layer: [Surface(name=AppWindowToken{7248de6 token=Token{b5bc441 ActivityRecord{5ccbf28 u0 sample.tencent.matrix/.SplashActivity t986}}})/@0x47abe83 - animation-leash#0] No local sync point found, barrierLayer : [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity$_2671#0]
`

**Comment by Andyload** [comment]
@scuzoutao 你看下transformClassesWithMatrixTraceTransformForDebug这个task输出有没抛出什么异常

**Comment by headfirst123** [comment]
你的来信已收到，谢谢
