### ISSUE TITLE
Demo打release跑不起来，移到项目里打开混淆会base.apk code is missing

### ISSUE THREAD

**Issue by scuzoutao** [Tencent/matrix#689]
异常类型：demo 上app 运行时异常，自己项目中打的包安装异常
手机型号：SM-G9650、小米10上都有问题
matrix版本：2.0.2
gradle版本：4.0.2

问题描述：
不开混淆没问题，开混淆就出问题
手动关联类似问题：
https://github.com/Tencent/matrix/issues/688
https://github.com/Tencent/matrix/issues/686

自己项目中报错：
adb: failed to install E:\xxx\debug\app-debug.apk: Failure [INSTALL_FAILED_INVALID_APK: Package couldn't be installed in /data/app/xxx-1: Package /data/app/xxx-1/base.apk code is missing

Demo报错：
`E/.tencent.matri: ----- class 'Lcom/tencent/matrix/trace/tracer/SignalAnrTracer;' cl=0x12efb9c0 -----
      objectSize=328 (120 from super)
      access=0x0008.0001
      super='java.lang.Class<com.tencent.matrix.trace.tracer.v>' (cl=0x12efb9c0)
      vtable (2 entries, 6 in super):
         0: void com.tencent.matrix.trace.tracer.SignalAnrTracer.h()
         1: void com.tencent.matrix.trace.tracer.SignalAnrTracer.j()
      direct methods (12 entries):
         0: void com.tencent.matrix.trace.tracer.SignalAnrTracer.<clinit>()
         1: void com.tencent.matrix.trace.tracer.SignalAnrTracer.<init>(b.c.a.m.d.c)
         2: void com.tencent.matrix.trace.tracer.SignalAnrTracer.l()
         3: boolean com.tencent.matrix.trace.tracer.SignalAnrTracer.m()
         4: void com.tencent.matrix.trace.tracer.SignalAnrTracer.n()
         5: void com.tencent.matrix.trace.tracer.SignalAnrTracer.o(java.lang.String, java.lang.String)
         6: void com.tencent.matrix.trace.tracer.SignalAnrTracer.onANRDumpTrace()
         7: void com.tencent.matrix.trace.tracer.SignalAnrTracer.onANRDumped()
         8: void com.tencent.matrix.trace.tracer.SignalAnrTracer.onPrintTrace()
         9: void com.tencent.matrix.trace.tracer.SignalAnrTracer.p()
        10: void com.tencent.matrix.trace.tracer.SignalAnrTracer.q()
        11: void com.tencent.matrix.trace.tracer.SignalAnrTracer.r(boolean)
      static fields (7 entries):
         0: boolean com.tencent.matrix.trace.tracer.SignalAnrTracer.d
         1: java.lang.String com.tencent.matrix.trace.tracer.SignalAnrTracer.e
         2: java.lang.String com.tencent.matrix.trace.tracer.SignalAnrTracer.f
         3: boolean com.tencent.matrix.trace.tracer.SignalAnrTracer.g
         4: boolean com.tencent.matrix.trace.tracer.SignalAnrTracer.h
         5: long com.tencent.matrix.trace.tracer.SignalAnrTracer.i
         6: java.lang.String com.tencent.matrix.trace.tracer.SignalAnrTracer.j
2021-12-07 15:54:35.578 29493-29493/? E/.tencent.matri: Failed to register native method com.tencent.matrix.trace.tracer.SignalAnrTracer.nativeInitSignalAnrDetective(Ljava/lang/String;Ljava/lang/String;)V in base.apk
2021-12-07 15:54:35.578 29493-29493/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sample.tencent.matrix, PID: 29493
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~V6oCTG7pRP4_6m_6K6K9mw==/sample.tencent.matrix-9E7_u_aa1BJAE002EKVSrA==/lib/arm64/libtrace-canary.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.tencent.matrix.trace.tracer.SignalAnrTracer.<clinit>(SignalAnrTracer.java:1)
        at b.c.a.m.a.run(TracePlugin.java:22)
        at b.c.a.m.c.start(TracePlugin.java:7)
        at sample.tencent.matrix.MatrixApplication.onCreate(MatrixApplication.java:58)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7096)
        at android.app.ActivityThread.access$1500(ActivityThread.java:265)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2021)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8170)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`

**Comment by borneygit** [comment]
我也遇到了这个问题，请问这个后面解决了吗

**Comment by scuzoutao** [comment]
> 我也遇到了这个问题，请问这个后面解决了吗

没有解决
