### ISSUE TITLE
couldn't find "libio-canary.so"

### ISSUE THREAD

**Issue by huangliqiang** [Tencent/matrix#7]
异常类型：app运行时异常

手机型号：如:vivo nex

手机系统版本：Android8.0

matrix版本:0.4.5

gradle版本：3.2.1

问题描述：无法运行couldn't find "libio-canary.so"

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.-1/base.apk"],nativeLibraryDirectories=[/data/app/com.-1/lib/arm, /data/app/com.-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libio-canary.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.tencent.matrix.iocanary.core.IOCanaryJniBridge.loadJni(IOCanaryJniBridge.java:95)
        at com.tencent.matrix.iocanary.core.IOCanaryJniBridge.install(IOCanaryJniBridge.java:43)
        at com.tencent.matrix.iocanary.core.IOCanaryCore.initDetectorsAndHookers(IOCanaryCore.java:83)
        at com.tencent.matrix.iocanary.core.IOCanaryCore.start(IOCanaryCore.java:49)
        at com.tencent.matrix.iocanary.IOCanaryPlugin.start(IOCanaryPlugin.java:62)
        at com..AppApplication.initMatrix(AppApplication.java:95)
        at com..AppApplication.onCreate(AppApplication.java:54)

**Comment by andansky** [comment]
couldn't find "libio-canary.so"  我也是这个问题

**Comment by MichaelJokAr** [comment]
same error

**Comment by astrozhou** [comment]
你切换到 dev 分支最新，matrix 升级到0.4.8试一下。之前没有编译其他架构的 so。此外 x86中跑 iocanary 是会 crash 的，可到常见问题中查看原因。

**Comment by SilenceDut** [comment]
same error

**Comment by hamberluo** [comment]
@astrozhou 0.48 版本还是缺少 arm64-v8a 和 x86_64 这两个

**Comment by MugWorld** [comment]
升级到了0.4.8不会报这个错了honor 6x  6.0系统

**Comment by hamberluo** [comment]
#29 提了一个 pr 修复

**Comment by astrozhou** [comment]
> #29 提了一个 pr 修复

666

**Comment by wuzhiqian** [comment]
android手机 荣耀V9  把matrix版本升级到0.4.8，0.4.10 还是报这个bug

**Comment by astrozhou** [comment]
close for completed

**Comment by wanlijiangshan** [comment]
我也是报couldn't find "libio-canary.so"的错误，demo可以跑，但是放到项目中就找不到了

**Comment by yaozhukuang** [comment]
+1


异常类型：app运行崩溃
手机型号：红米note5
手机系统版本：Android8.1.0
matrix版本:0.4.10
gradle版本：3.1.0

问题描述：无法运行couldn't find "libio-canary.so"

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mi.global.bbs-UWhQFFFo_JBAu0CWTq9jrw==/base.apk"],nativeLibraryDirectories=[/data/app/com.mi.global.bbs-UWhQFFFo_JBAu0CWTq9jrw==/lib/arm64, /data/app/com.mi.global.bbs-UWhQFFFo_JBAu0CWTq9jrw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libio-canary.so"
