### ISSUE TITLE
android.enableR8=false下插桩无法打混淆包

### ISSUE THREAD

**Issue by nathanielalexislo** [Tencent/matrix#701]
[exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Could not determine the dependencies of task ':android:mergeDexFullRelease'.
     [exec] > Could not create task ':android:dexBuilderFullRelease'.
     [exec]    > Could not create task ':android:matrixFullReleaseTrace'.
     [exec]       > java.lang.NullPointerException (no error message)
     [exec] 
     [exec] * Try:
     [exec] Run with --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':android:mergeDexFullRelease'.
     [exec] 	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:69)
     [exec] 	at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
     [exec] 	at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:161)
     [exec] 	at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:129)
     [exec] 	at org.gradle.execution.plan.DefaultExecutionPlan.doAddNodes(DefaultExecutionPlan.java:164)

**Comment by nathanielalexislo** [comment]
已解决，gradle加个参数，强制走混淆前打包
transformInjectionForced = true
