### ISSUE TITLE
ActivityManager.getMemoryInfo 偶现 DeadSystemException  

### ISSUE THREAD

**Issue by gdutxiaoxu** [Tencent/matrix#704]
异常类型：app 运行时异常

手机型号：华为 P20

手机系统版本：Android 10.0

matrix版本： 2.0.1

gradle版本：4.1.0

问题描述：ActivityManager.getMemoryInfo 偶现 DeadSystemException  

堆栈/日志：
java.lang.RuntimeException: android.os.DeadSystemException  

    at android.app.ActivityManager.getMemoryInfo(ActivityManager.java:2368)  

    at com.tencent.matrix.util.DeviceUtil.getMemFree(DeviceUtil.java:193)  

    at com.tencent.matrix.util.DeviceUtil.getDeviceInfo(DeviceUtil.java:82)  

    at com.tencent.matrix.trace.tracer.EvilMethodTracer$AnalyseTask.analyse(EvilMethodTracer.java:182)  

    at com.tencent.matrix.trace.tracer.EvilMethodTracer$AnalyseTask.run(EvilMethodTracer.java:204)  

    at android.os.Handler.handleCallback(Handler.java:751)  

    at android.os.Handler.dispatchMessage(Handler.java:95)  

    at android.os.Looper.loop(Looper.java:154)  

    at android.os.HandlerThread.run(HandlerThread.java:61)  

Caused by: android.os.DeadSystemException  

    ... 9 more  

android.os.DeadSystemException  

    at android.app.ActivityManager.getMemory...

**Comment by gryamy** [comment]
AMS 偶现报错是有可能的，这里应该可以保护下。

**Comment by gdutxiaoxu** [comment]
是的，目前在项目中我也是做了保护。
@gryamy
