### ISSUE TITLE
NullPointerException: class name is null

### ISSUE THREAD

**Issue by gao746700783** [Tencent/matrix#736]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```
异常类型：app 运行时异常/编译异常

手机型号：如: Mi  8

手机系统版本：如:Android Q

matrix版本：如:2.0.5

gradle版本：如: 4.2.0

问题描述：如：在 android O 出现系统不兼容 

堆栈/日志：

2022-03-31 19:02:13.638 23120-23167/com.example.myapplication V/Matrix.ActivityRefWatcher: triggering gc...
2022-03-31 19:02:13.712 23120-23167/com.example.myapplication I/e.myapplicatio: Explicit concurrent copying GC freed 18(32KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 3811KB/5081KB, paused 252us total 73.783ms
2022-03-31 19:02:13.716 23120-23162/com.example.myapplication V/Matrix.ActivityRefWatcher: gc was triggered.
2022-03-31 19:02:13.716 23120-23162/com.example.myapplication I/Matrix.LeakProcessor.ManualDump: analyze cost=14363ms refString=MATRIX_RESCANARY_REFKEY_com.example.myapplication.ui.MainActivity_1d74662d81144dc0bf9285abb70d0a3f
2022-03-31 19:02:13.717 23120-23162/com.example.myapplication I/Matrix.LeakProcessor.ManualDump: leakFound,refcChain = Leak Reference:android.app.Activity$1 this$0 (anonymous subclass of android.app.IRequestFinishCallback$Stub);com.example.myapplication.ui.MainActivity instance;
2022-03-31 19:02:13.720 23120-23162/com.example.myapplication I/Matrix.DefaultPluginListener: report issue content: tag[memory]type[0];key[null];content[{"dump_mode":"MANUAL_DUMP","activity":"com.example.myapplication.ui.MainActivity","ref_key":"MATRIX_RESCANARY_REFKEY_com.example.myapplication.ui.MainActivity_1d74662d81144dc0bf9285abb70d0a3f","leak_detail":"Leak Reference:android.app.Activity$1 this$0 (anonymous subclass of android.app.IRequestFinishCallback$Stub);com.example.myapplication.ui.MainActivity instance;","cost_millis":"16487","tag":"memory","process":"com.example.myapplication","time":1648724533718}]
2022-03-31 19:02:13.721 23120-23162/com.example.myapplication I/Matrix.LeakProcessor.ManualDump: shown notification!!!3
    
    --------- beginning of crash
2022-03-31 19:02:13.723 23120-23162/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: default_matrix_thread
    Process: com.example.myapplication, PID: 23120
    java.lang.NullPointerException: class name is null
        at android.content.ComponentName.<init>(ComponentName.java:117)
        at android.content.Intent.setClassName(Intent.java:9701)
        at com.tencent.matrix.resource.processor.ManualDumpProcessor.sendResultNotification(ManualDumpProcessor.java:97)
        at com.tencent.matrix.resource.processor.ManualDumpProcessor.access$100(ManualDumpProcessor.java:38)
        at com.tencent.matrix.resource.processor.ManualDumpProcessor$1.onDumpComplete(ManualDumpProcessor.java:82)
        at com.tencent.matrix.resource.processor.ManualDumpProcessor$2.run(ManualDumpProcessor.java:156)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-03-31 19:02:13.756 23120-23162/com.example.myapplication I/Process: Sending signal. PID: 23120 SIG: 9

**Comment by Yves0** [comment]
初始化 resource-canary 时配置一下 setManualDumpTargetActivity，manual dump 模式下会弹通知，这个是点击通知跳转的 Activity。下个版本会补充判空检查
```Java
            ResourceConfig resourceConfig = new ResourceConfig.Builder()
                .dynamicConfig(dynamicConfig)
                .setAutoDumpHprofMode(mode)
                .setManufacture(Build.MANUFACTURER)
                .setManualDumpTargetActivity("com.package.name.YourActivity") // here
                .build();
            Plugin resourcePlugin = new ResourcePlugin(resourceConfig);
```
