### ISSUE TITLE
2.0.8 android.graphics.drawable.Drawable.setAlpha(int) 闪退问题还是存在

### ISSUE THREAD

**Issue by lixiangkai1987** [Tencent/matrix#755]
java.lang.RuntimeException: Unable to destroy activity {com.xjj.cloud.marsOa/com.xjj.newframe.module_cloud_disk.activity.CloudDiskMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setAlpha(int)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5506)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5539)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
        at com.xjj.cloud.perfmonlib.cockroach.Cockroach$2.handleMessage(Cockroach.java:113)
        at com.didiglobal.booster.instrument.ActivityThreadCallback.handleMessage(ActivityThreadCallback.java:71)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8103)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setAlpha(int)' on a null object reference
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setColorViewAlpha(SwipeRefreshLayout.java:299)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.reset(SwipeRefreshLayout.java:222)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onDetachedFromWindow(SwipeRefreshLayout.java:295)
        at android.view.View.dispatchDetachedFromWindow(View.java:21161)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3967)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3959)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3959)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3959)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5591)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5562)
        at android.view.ViewGroup.removeView(ViewGroup.java:5493)
        at androidx.viewpager.widget.ViewPager.removeView(ViewPager.java:1507)
        at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.java:452)
        at androidx.fragment.app.SpecialEffectsController$1.run(SpecialEffectsController.java:211)
        at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.java:695)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:744)
        at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:597)
        at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:332)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3132)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:334)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:330)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:278)
        at com.xjj.AGUI.arch.AGUIMvvMBaseActivity.onDestroy(AGUIMvvMBaseActivity.java:524)
        at android.app.Activity.performDestroy(Activity.java:8544)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
E/AndroidRuntime:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5493)
        	... 15 more

**Comment by Yves0** [comment]
请问有没有能复现的 demo 呢？

**Comment by lixiangkai1987** [comment]
偶发的，不是必现，页面框架是activity下有viewpager，viewpager下是多个fragment，每个fragment都带有swiperefreshlayout

还有一种布局是面包屑结构，一样每个每个fragment都带有swiperefreshlayout

返回结束activity的时候就会偶发闪退

**Comment by Airoure** [comment]
我这也有一样的问题
