### ISSUE TITLE
at com.tencent.matrix.trace.MethodCollector$TraceClassAdapter.visit(MethodCollector.java:285)

### ISSUE THREAD

**Issue by mikelhm** [Tencent/matrix#756]
install apk  时有异常堆栈
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/10327642/172782673-bd166dd6-3e72-4275-95aa-b04999215adb.png">

**Comment by mikelhm** [comment]
version  master 2.0.8

**Comment by Yves0** [comment]
上游 transform 是否有 ASM 插桩相关逻辑，把 class 插坏了，className 或者 superName 变成 null 了

**Comment by mikelhm** [comment]
> 

上游并没有ASM 插桩相关逻辑

**Comment by mikelhm** [comment]
> 上游 transform 是否有 ASM 插桩相关逻辑，把 class 插坏了，className 或者 superName 变成 null 了

上游并没有 ASM 插桩相关逻辑

**Comment by igottime** [comment]
[排除掉对META-INFO和mudule-info](https://github.com/Tencent/matrix/pull/790/commits/890fba44ab101fc28cf33529dd472d5fa0085c8a)

**Comment by Larnoo** [comment]
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/modules-2/files-2.1/androidx.collection/collection/1.1.0/1f27220b47669781457de0d600849a5de0e89909/collection-1.1.0.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/50.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/0f61a05d93459a3008952a6d99218c47/core-runtime-2.1.0-runtime.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/51.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/7f2a72e0107f879ccda6e03cd3497aeb/interpolator-1.0.0-runtime.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/53.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/modules-2/files-2.1/androidx.arch.core/core-common/2.1.0/b3152fc64428c9354344bd89848ecddc09b6f07e/core-common-2.1.0.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/52.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/2299d16dda0e0d320dc2d2df94443928/localbroadcastmanager-1.0.0-runtime.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/55.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/15ba66f8d3062c02f089055c565f33f4/documentfile-1.0.0-runtime.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/54.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/0ef462a85ca11c868b4088e6fa3c41a7/print-1.0.0-runtime.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/56.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/5cf12042025661ea94bd8255459832e7/jetified-kotlin-stdlib-1.6.21.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/58.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/5929ff2481213b04185d7af16ccdacde/jetified-tinker-ziputils-1.9.2.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/59.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.4.0/77e7b6bbe9803d890343716dd824dfdbc0f6fe77/annotation-1.4.0.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/57.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/904f59063bd5bfb109043c11b6e0f969/jetified-kotlin-stdlib-common-1.6.21.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/60.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/f0e99c204119252e8bc9188fad60a2c8/jetified-annotations-13.0.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/61.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/9c06f2651eddb51f88af7ed68f4f7cca/jetified-haha-2.0.3.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/62.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/transforms-2/files-2.1/14f8dfdb7f7e74d423c5af179890a8c6/jetified-annotation-experimental-1.0.0-runtime.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/63.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/.gradle/caches/modules-2/files-2.1/androidx.constraintlayout/constraintlayout-solver/2.0.1/30988fe2d77f3fe3bf7551bb8a8b795fad7e7226/constraintlayout-solver-2.0.1.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/64.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/android_app/matrix/samples/sample-android/libkt/build/intermediates/runtime_library_classes_jar/debug/classes.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/65.jar
[D][Matrix.Trace] CollectJarInputTask input /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/debug/R.jar -> output /home/larno/android_app/matrix/samples/sample-android/app/build/intermediates/transforms/MatrixTraceTransform/debug/66.jar
java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at com.tencent.matrix.trace.MethodCollector$TraceClassAdapter.visit(MethodCollector.java:285)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:524)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at com.tencent.matrix.trace.MethodCollector$CollectJarTask.run(MethodCollector.java:172)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at com.tencent.matrix.trace.MethodCollector$TraceClassAdapter.visit(MethodCollector.java:285)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:524)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at com.tencent.matrix.trace.MethodCollector$CollectJarTask.run(MethodCollector.java:172)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
