### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by lodqc** [Tencent/matrix#758]
异常类型：app 运行时异常

手机型号：realme

手机系统版本：Android 12

matrix版本：2.0.8

gradle版本：4.1.0

问题描述：
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:464)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at com.tencent.matrix.resource.processor.ManualDumpProcessor.sendResultNotification(ManualDumpProcessor.java:103)
        at com.tencent.matrix.resource.processor.ManualDumpProcessor.access$100(ManualDumpProcessor.java:38)
        at com.tencent.matrix.resource.processor.ManualDumpProcessor$1.onDumpComplete(ManualDumpProcessor.java:82)
        at com.tencent.matrix.resource.processor.ManualDumpProcessor$2.run(ManualDumpProcessor.java:156)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by lodqc** [comment]
已降低目标版本为30，可以正常显示通知栏

**Comment by WangcWj** [comment]
Android 12的新增加的对PendingIntent的FLAG_UPDATE_CURRENT的限制。
