### ISSUE TITLE
Matrix.init error : NullPointerException

### ISSUE THREAD

**Issue by MichaelJokAr** [Tencent/matrix#8]
```
异常类型：app运行时异常/编译异常
初始化异常
手机型号：如:Nexus 5(如是编译异常，则可以不填)
模拟器 x*6
手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)
android P
matrix版本：如:0.4.5
0.4.5
gradle版本：如:2.10
3.1.0
问题描述：如：在android O 出现系统不兼容 

堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Matrix."关键字;

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.HashSet.iterator()' on a null object reference
        at com.tencent.matrix.Matrix.<init>(Matrix.java:46)
        at com.tencent.matrix.Matrix.<init>(Matrix.java:32)
        at com.tencent.matrix.Matrix$Builder.build(Matrix.java:163)
```

我的初始化代码：
```
 private void initMatrix(){
        Matrix.Builder builder = new Matrix.Builder(this); // build matrix
        builder.patchListener(new TestPluginListener(this)); // add general pluginListener


        //init matrix
        Matrix.init(builder.build());

    }
```

**Comment by astrozhou** [comment]
你的代码中没有 add 任何的 plugin，那 Matrix 就没有任何效果，你需要最少加一个 plugin
