### ISSUE TITLE
 java -jar ApkChecker.jar --config config.json 出错

### ISSUE THREAD

**Issue by hymlv** [Tencent/matrix#805]
[E][Matrix.ApkJob] Task executor execute with error:com.tencent.matrix.apk.model.exception.TaskExecuteException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonArray
java.util.concurrent.ExecutionException: com.tencent.matrix.apk.model.exception.TaskExecuteException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonArray
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:526)
        at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:499)
        at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
        at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)
Caused by: com.tencent.matrix.apk.model.exception.TaskExecuteException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonArray
        at com.tencent.matrix.apk.model.task.ManifestAnalyzeTask.call(ManifestAnalyzeTask.java:91)
        at com.tencent.matrix.apk.model.task.ManifestAnalyzeTask.call(ManifestAnalyzeTask.java:42)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonArray
        at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:181)
        at com.tencent.matrix.apk.model.task.util.ManifestParser.handleEndElement(ManifestParser.java:130)
        at com.tencent.matrix.apk.model.task.util.ManifestParser.parse(ManifestParser.java:79)
        at com.tencent.matrix.apk.model.task.ManifestAnalyzeTask.call(ManifestAnalyzeTask.java:84)

**Comment by zktzktzkt** [comment]
我也遇到了同样的问题
