### ISSUE TITLE
执行报错：java -jar /xxxx/matrix-apk-canary-2.0.8.jar --config  /xxxx/apk_config.json

### ISSUE THREAD

**Issue by peienliudao** [Tencent/matrix#816]
系统：Mac
执行上述命令报错

java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1024)
	at com.tencent.matrix.apk.model.result.JobJsonResult.writeJsonArrayStart(JobJsonResult.java:56)
	at com.tencent.matrix.apk.model.result.JobJsonResult.output(JobJsonResult.java:112)
	at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:540)
	at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:499)
	at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
	at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)

**Comment by byedo** [comment]
> 已经解决了。

怎么解决的能讲一下吗？
