### ISSUE TITLE
在gradle 7.5， 编译报错： Matrix.MethodTracer input:classes e:NestHost requires ASM7

### ISSUE THREAD

**Issue by itachsheep** [Tencent/matrix#837]
异常类型：编译异常

matrix版本：2.1.0

gradle版本：如:  7.5

堆栈/日志：

[E][Matrix.MethodTracer] [innerTraceMethodFromSrc] input:classes e:NestMember requires ASM7
java.nio.file.DirectoryNotEmptyException: /Users/d/project/bingbon3/bingbon-android3/app/build/intermediates/transforms/MatrixTraceTransform/bingintl/debug/336
        at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:586)
        at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
        at java.base/java.nio.file.Files.copy(Files.java:1295)
        at com.tencent.matrix.trace.MethodTracer.innerTraceMethodFromSrc(MethodTracer.java:183)
        at com.tencent.matrix.trace.MethodTracer.access$000(MethodTracer.java:63)
        at com.tencent.matrix.trace.MethodTracer$1.run(MethodTracer.java:102)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[E][Matrix.MethodTracer] [innerTraceMethodFromSrc] input:classes e:NestMember requires ASM7
java.nio.file.DirectoryNotEmptyException: /Users/d/project/bingbon3/bingbon-android3/app/build/intermediates/transforms/MatrixTraceTransform/bingintl/debug/336
        at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:586)
        at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
        at java.base/java.nio.file.Files.copy(Files.java:1295)
        at com.tencent.matrix.trace.MethodTracer.innerTraceMethodFromSrc(MethodTracer.java:183)
        at com.tencent.matrix.trace.MethodTracer.access$000(MethodTracer.java:63)
        at com.tencent.matrix.trace.MethodTracer$1.run(MethodTracer.java:102)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[E][Matrix.MethodTracer] [innerTraceMethodFromJar] input:/Users/d/project/bingbon3/bingbon-android3/module_widget/build/intermediates/runtime_library_classes_jar/debug/classes.jar output:/Users/d/project/bingbon3/bingbon-android3/app/build/intermediates/transforms/MatrixTraceTransform/bingintl/debug/312.jar e:NestHost requires ASM7
[E][Matrix.MethodTracer] [innerTraceMethodFromJar] input:/Users/admin/.gradle/caches/transforms-3/3099a438e90047218ea1b7e3a12a387f/transformed/jetified-bcprov-jdk18on-1.71.jar output:/Users/d/project/bingbon3/bingbon-android3/app/build/intermediates/transforms/MatrixTraceTransform/bingintl/debug/299.jar e:NestHost requires ASM7android3/lib_update/build/intermediates/runtime_library_classes_jar/debug/classes.jar output:/Users/d/project/bingbon3/bingbon-android3/app/build/intermediates/transforms/MatrixTraceTransform/bingintl/debug/321.jar e:NestHost requires ASM7
[E][Matrix.MethodTracer] [innerTraceMethodFromJar] input:/Users/d/project/bingbon3/bingbon-android3/module_share/build/intermediates/runtime_library_classes_jar/debug/classes.jar output:/Users/d/project/bingbon3/bingbon-android3/app/build/intermediates/transforms/MatrixTraceTransform/bingintl/debug/309.jar e:NestHost requires ASM7
[E][Matrix.MethodTracer] [innerTraceMethodFromJar] input:/Users/d/project/bingbon3/bingbon-android3/lib_klinechart/build/intermediates/runtime_library_classes_jar/debug/classes.jar output:/Users/d/project/bingbon3/bingbon-android3/app/build/intermediates/transforms/MatrixTraceTransform/bingintl/debug/314.jar e:NestHost requires ASM7
[E][Matrix.MethodTracer] [innerTraceMethodFromJar] input:/Users/d/project/bingbon3/bingbon-android3/lib_constant/build/intermediates/runtime_library_classes_jar/debug/classes.jar 
> Task :app:transformClassesWithMatrixTraceTransformForBingintlDebug FAILED

**Comment by itachsheep** [comment]
补充：
build tools 版本：  'com.android.tools.build:gradle:7.4.2'
gradle 版本： https\://services.gradle.org/distributions/gradle-7.5-all.zip

**Comment by Jun1orChan** [comment]
借楼；
同样问题，我看了源码，源码在 AGP 7 传入的是：Opcodes.ASM6，导致的问题，官方有兼容计划吗；

**Comment by Vihanmy** [comment]
大佬们, 怎么解决的, 我看文档说只有 agp 4.x.x 的几个版本才能使用, 现在的项目动不动就是  6.0 或者 7.0 了吧. 有其他的框架推荐吗请问

**Comment by initialjie** [comment]
同样遇到这个问题，编译报异常，但是依然能成功出包，不知道运行时是否会有问题

**Comment by justziyang** [comment]
大佬们有解决方案吗？
