### ISSUE TITLE
apkchecker在mac系统下不生成结果文件

### ISSUE THREAD

**Issue by byedo** [Tencent/matrix#875]
mac系统运行apkchecker 2.1.0和2.0.8都不生成最终的结果文件，才开始路径报错

java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:356)
	at java.base/java.io.File.createNewFile(File.java:1045)
	at com.tencent.matrix.apk.model.result.JobHtmlResult.writeHtmlStart(JobHtmlResult.java:59)
	at com.tencent.matrix.apk.model.result.JobHtmlResult.output(JobHtmlResult.java:109)
	at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:540)
	at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:499)
	at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
	at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)

后面修改了路径，不报错了，但是还是没有生成结果文件，怎么调试一下

**Comment by byedo** [comment]
把路径改成
