### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libtrace-canary.so" not found

### ISSUE THREAD

**Issue by hongyi0609** [Tencent/matrix#882]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```
Properties
avd.ini.displayname      Pixel_3a_API_34_extension_level_7_x86_64
avd.ini.encoding         UTF-8
AvdId                    Pixel_3a_API_34_extension_level_7_x86_64
disk.dataPartition.size  6442450944
hw.accelerometer         yes
hw.arc                   false
hw.audioInput            yes
hw.battery               yes
hw.camera.back           emulated
hw.camera.front          emulated
hw.cpu.ncore             4
hw.device.hash2          MD5:0e6953ebf01bdc6b33a2f54746629c50
hw.device.manufacturer   Google
hw.device.name           pixel_3a
hw.dPad                  no
hw.gps                   yes
hw.gpu.enabled           yes
hw.gpu.mode              auto
hw.keyboard              yes
hw.lcd.density           440
hw.lcd.height            2220
hw.lcd.width             1080
hw.mainKeys              no
hw.ramSize               1536
hw.sdCard                yes
hw.sensors.orientation   yes
hw.sensors.proximity     yes
hw.trackBall             no
image.androidVersion.api 34
image.sysdir.1           system-images/android-34/google_apis/x86_64/
PlayStore.enabled        false
runtime.network.latency  none
runtime.network.speed    full
snapshot.present         no
tag.display              Google APIs
tag.id                   google_apis
vm.heapSize              256

```

```
异常类型：app 运行时异常/编译异常

手机型号： pixel_3a

手机系统版本：API_34

matrix版本：如: 2.1.0

gradle版本：如: 7.5

问题描述：如：在 android API 34 出现系统不兼容 

堆栈/日志：
1. 如是编译异常，请在执行 gradle 命令时，加上 --stacktrace;
2. 日志我们需要过滤" Matrix. "关键字;
```
FATAL EXCEPTION: main
                                                                                                    Process: com.edwin.idea, PID: 13831
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libtrace-canary.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.tencent.matrix.trace.tracer.SignalAnrTracer.<clinit>(SignalAnrTracer.java:92)
                                                                                                    	at com.tencent.matrix.trace.TracePlugin$1.run(TracePlugin.java:124)
                                                                                                    	at com.tencent.matrix.trace.TracePlugin.start(TracePlugin.java:147)
                                                                                                    	at core.IdeaApplication.initMatrix(IdeaApplication.java:142)
                                                                                                    	at core.IdeaApplication.onCreate(IdeaApplication.java:114)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by hongyi0609** [comment]
我用的模拟器出的问题
