### ISSUE TITLE
java.lang.NoClassDefFoundError: com.tencent.matrix.trace.core.MethodBeat

### ISSUE THREAD

**Issue by nysin** [Tencent/matrix#91]
java.lang.NoClassDefFoundError: com.tencent.matrix.trace.core.MethodBeat
        at com.tencent.tinker.loader.TinkerUncaughtHandler.<init>(TinkerUncaughtHandler.java:42)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:147)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:514)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4669)
        at android.app.ActivityThread.access$1500(ActivityThread.java:174)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:222)
        at android.app.ActivityThread.main(ActivityThread.java:5484)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
        at dalvik.system.NativeStart.main(Native Method)
```
异常类型：app 运行时异常/编译异常

手机型号：oppo r7

手机系统版本：如:Android4.4

matrix版本 0.4.7

gradle版本：3.0.1

问题描述：无法启动

**Comment by changelcai** [comment]
应该是MethodBeat没有打包进apk，编译过程中有报错吗？

**Comment by hfutgl** [comment]
我今天把resourcecannary打包成aar放到工程里也出现这个问题，新建一个工程再放aar没问题，分析中

**Comment by imtianx** [comment]
同样遇到这个问题，我这里是没有依赖 `matrix-trace-canary` 并且设置了 `enable = true`,添加依赖或者设置为 `false` 解决。

**Comment by chengfangpeng** [comment]
我也遇到相同的问题，然后，我把MethodBeat keep到dex主包然后问题解决了

**Comment by DozenWang** [comment]
同样遇到这个问题，是由于MultiDex引起的，主要在5.0以下机型，methodbeat 在attachBaseContext 入口处做了插桩，MultiDex.install 调用时机较晚，解决方法可以把MethodBeat keep到主dex中，还可以在blackMehtodList中添加 `-keepclass  applicationName` ，不在application中插桩

**Comment by qqyumidi** [comment]
项目中也发现了同样的问题，5.0以下机型出现。通过配置maindex文件解决。
multiDexKeepProguard file('multidex-config.pro')
-keep class com.tencent.matrix.trace.core.MethodBeat
